<a href="https://colab.research.google.com/github/HagiwaraNorito/DeepLearning2022Late/blob/main/%E3%83%A2%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%AB%E3%81%A8%E3%83%A9%E3%82%A4%E3%83%96%E3%83%A9%E3%83%AA%E3%81%AE%E4%BD%BF%E7%94%A80920.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#モジュールをつかう
import文でモジュールを読み込んで使う
例）math

In [1]:
#mathモジュールを読み込む
import math
print(math.pi)
print(math.pow(5,2))
print(math.sqrt(9))

3.141592653589793
25.0
3.0


##Numpy-－数値計算用の便利なライブラリ

 https://numpy.org

In [2]:
import numpy as np


##numpy配列()


In [3]:
a=np.array([5,7,3,1,4,3])
print(a)

[5 7 3 1 4 3]


##Numpyで配列の操作をしてみる
配列を構成しなおす


In [4]:
print(a)
b=a.reshape([3,2])
print(b)


[5 7 3 1 4 3]
[[5 7]
 [3 1]
 [4 3]]


##Numpy配列の中身を初期化して作る

In [5]:
c=np.zeros((3,4))
print(c)
#ランダムな値が入った配列をつくる
np.random.seed(0)
r=np.random.rand(3,4)
print(r)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]]


## Numpyのスライスのやりかた
###基本
スライスの指定の仕方
[start:stop:step]
で指定する

In [6]:
l=list(range(10))
print(l)
print(l[4:8])
print(l[ : :-1])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[4, 5, 6, 7]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


##一次元のNumpy配列(ndarray)におけるスライス


In [7]:
a=np.arange(10)
print(a)
print(a[2:8])
print(a[2:8:2])
print(a[2:8:3])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7]
[2 4 6]
[2 5]


##一次元配列のndarrayのスライスに代入

In [8]:
print(a)
a[3:6] = 100
print(a)
a[3:6]=[100,200,300]
print(a)
#a[3:6]=[100,200,300,400]
a=np.arange(10)
print(a)
a[2:8:2]=100
print(a)

[0 1 2 3 4 5 6 7 8 9]
[  0   1   2 100 100 100   6   7   8   9]
[  0   1   2 100 200 300   6   7   8   9]
[0 1 2 3 4 5 6 7 8 9]
[  0   1 100   3 100   5 100   7   8   9]


##多次元並列のndarrayのスライス

In [9]:
a=np.arange(12).reshape((3,4))
print(a)
print(a[1:, 1:3])
b=np.arange(20).reshape((5,4))
print(b)
print(b[1:, 1:3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 5  6]
 [ 9 10]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 5  6]
 [ 9 10]
 [13 14]
 [17 18]]


#多次元のndarrayへのスライス

In [13]:
# 要素数12の3行4列の2次元配列を作る
a = np.arange( 12 ).reshape( 3,4 )
print(a)
# 5, 6, 9, 10 の部分をスライス
print( a[ 1: , 1:3 ] )
a[1: , 1:3] = 100
print(a)
a = np.arange( 12 ).reshape( 3,4 )
# 多次元での上書きにリストを使う
a[ 1:, 1:3 ] = [100, 200]
print( a )
# 多次元の上書きに2次元のリストを使う
a[ 1:, 1:3 ] = [  [100, 200], [300, 400]  ]
print( a )

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 5  6]
 [ 9 10]]
[[  0   1   2   3]
 [  4 100 100   7]
 [  8 100 100  11]]
[[  0   1   2   3]
 [  4 100 200   7]
 [  8 100 200  11]]
[[  0   1   2   3]
 [  4 100 200   7]
 [  8 300 400  11]]


##多次元のndarrayへのstopを使ったスライスでの代入

In [12]:
# 要素数12 3行4列のndarrayを作って変数aに代入
a = np.arange(12).reshape( (3, 4) )
print(a)
# スライスにstep使ってみる　4、6、8、10抜き出す
print( a[ 1: , ::2 ] )
# 0, 3, 4, 7 抜き出す
print( a[ :2:, : :3  ] )
a[ 1: , ::2 ] = 100 # 4, 6, 8, 10だったところを100で上書き
print(a)
# 4, 6, 8, 10だったところをリストで上書き
a[ 1: , ::2 ] = [100, 200]
print( a )
# 4, 6, 8, 10だったところを多次元のリストで上書き
a[ 1: , ::2 ] = [  [ 100, 200 ], [ 300, 400 ]  ]
print( a )

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 4  6]
 [ 8 10]]
[[0 3]
 [4 7]]
[[  0   1   2   3]
 [100   5 100   7]
 [100   9 100  11]]
[[  0   1   2   3]
 [100   5 200   7]
 [100   9 200  11]]
[[  0   1   2   3]
 [100   5 200   7]
 [300   9 400  11]]
